inherit_from: .rubocop_todo.yml

# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'storage/**/*'
    - 'public/**/*'
    - 'app/assets/builds/**/*'

# Style Configuration
Style/Documentation:
  Enabled: false  # OK for non-library code

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/ClassAndModuleChildren:
  EnforcedStyle: compact  # Allow Admin::ProductsController

# Layout Configuration
Layout/LineLength:
  Max: 120  # Set reasonable limit instead of disabling
  Exclude:
    - 'test/**/*'
    - 'config/routes.rb'
    - 'config/initializers/devise.rb'
    - 'app/controllers/admin_controller.rb'
    - 'app/controllers/admin/reports_controller.rb'

# Metrics Configuration - Set reasonable limits instead of disabling
Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'config/routes.rb'
    - 'config/environments/*.rb'

Metrics/AbcSize:
  Max: 25  # Warn on complex methods
  Exclude:
    - 'test/**/*'
    - 'db/migrate/*.rb'
    - 'app/controllers/quantities_controller.rb'
    - 'app/controllers/quantities/**/*'
    - 'app/controllers/admin_controller.rb'
    - 'app/controllers/admin/reports_controller.rb'
    - 'app/controllers/admin/products_controller.rb'

Metrics/MethodLength:
  Max: 25  # Encourage shorter methods
  Exclude:
    - 'test/**/*'
    - 'db/migrate/*.rb'
    - 'app/controllers/admin_controller.rb'
    - 'app/controllers/admin/reports_controller.rb'

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'test/**/*'

Metrics/ModuleLength:
  Max: 200
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'test/**/*'
    - 'app/controllers/admin/reports_controller.rb'

Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - 'test/**/*'
    - 'app/controllers/admin/products_controller.rb'
    - 'app/controllers/admin/reports_controller.rb'

Style/ConditionalAssignment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

# Linting Configuration
Lint/NonLocalExitFromIterator:
  Enabled: true  # This should be caught
